# ───────────── Finances News ─────────────
- name: financesnews
  list_url: "https://fnh.ma/articles/actualite-financiere-maroc"
  base_url: "https://fnh.ma"
  selectors:
    container: "div.row"                       # bloque <div class="row">…</div>
    headline:  "h2 a"                          # titular + enlace
    link_attr: "href"
    description: "div.list_article_detail p"   # primer párrafo
    image: "img::attr(src)"                    # miniatura
    date:  "label.itemdate"                    # «Vendredi 25 Juillet 2025»
  date_regex: "\\b(\\d{1,2})\\s+([A-Za-zéû]+)\\s+(\\d{4})\\b"
  month_map: &fr_months
    Janvier:    "01"
    Février:    "02"
    Mars:       "03"
    Avril:      "04"
    Mai:        "05"
    Juin:       "06"
    Juillet:    "07"
    Août:       "08"
    Septembre:  "09"
    Octobre:    "10"
    Novembre:   "11"
    Décembre:   "12"
