- name: financesnews
  list_url: "https://fnh.ma/articles/actualite-financiere-maroc"
  base_url: "https://fnh.ma"
  selectors:
    container: "div.td-ss-main-content div.td_module_16"
    headline: "h3.entry-title a"
    description: "div.td-excerpt"
    link_attr: "href"
    image: "img.entry-thumb::attr(src)"
    date: "div.td-post-date"
  date_regex: "\\b(\\d{1,2})\\s+([A-Za-zéû]+)\\s+(\\d{4})\\b"
  month_map:
    Janvier: "01"
    Février: "02"
    Mars: "03"
    Avril: "04"
    Mai: "05"
    Juin: "06"
    Juillet: "07"
    Août: "08"
    Septembre: "09"
    Octobre: "10"
    Novembre: "11"
    Décembre: "12"
- name: leconomiste
  list_url: "https://www.leconomiste.com/categorie/March%C3%A9s-Financiers"
  base_url: "https://www.leconomiste.com"
  selectors:
    # contenedor de cada noticia
    container: "div.views-row"
    # titular + enlace
    headline: "h2 a"
    link_attr: "href"
    # snippet (si lo hay)
    description: "div.views-field-field_description, p"
    # miniatura
    image: "img::attr(src)"
    # fecha «Le 24/07/2025»
    date: "span.date, span.date-display-single"
  # dd/mm/aaaa
  date_regex: "Le\\s+(\\d{1,2})\\/(\\d{1,2})\\/(\\d{2,4})"
