# Multi-source configuration for Moroccan Finance Scraper
# Each source defines how to fetch and parse articles

# ===== BourseNews (Original Source) =====
- name: boursenews
  type: html
  list_url: "https://boursenews.ma/articles/marches"
  base_url: "https://boursenews.ma"
  allowed_domains:
    - "boursenews.ma"
    - "www.boursenews.ma"
  selectors:
    container: "div.list_item div.row"
    headline: "h3 a"
    link_attr: "href"
    description: "p"
    image: "img"
    date: "h3 a span"
  # Lazy-load image attributes to check (in order)
  image_attrs:
    - "data-src"
    - "data-lazy-src"
    - "data-original"
    - "src"
  date_regex: "\\b(\\d{1,2})\\s+([A-Za-z\u00c0-\u00ff]+)\\s+(\\d{4})\\b"
  month_map: &fr_months
    Janvier: "01"
    Février: "02"
    Mars: "03"
    Avril: "04"
    Mai: "05"
    Juin: "06"
    Juillet: "07"
    Août: "08"
    Aout: "08"
    Septembre: "09"
    Octobre: "10"
    Novembre: "11"
    Décembre: "12"
    Decembre: "12"

# ===== Finances News =====
- name: financesnews
  type: html
  list_url: "https://fnh.ma/articles/actualite-financiere-maroc"
  base_url: "https://fnh.ma"
  allowed_domains:
    - "fnh.ma"
    - "www.fnh.ma"
  selectors:
    container: "div.row"
    headline: "h2 a"
    link_attr: "href"
    description: "div.list_article_detail p"
    image: "img"
    date: "label.itemdate"
  image_attrs:
    - "src"
  date_regex: "\\b(\\d{1,2})\\s+([A-Za-z\u00c0-\u00ff]+)\\s+(\\d{4})\\b"
  month_map: *fr_months

# ===== L'Economiste (WP-JSON API) =====
- name: leconomiste
  type: wp-json
  api_url: "https://www.leconomiste.com/wp-json/wp/v2/posts?categories=112&per_page=20&_embed"
  base_url: "https://www.leconomiste.com"
  allowed_domains:
    - "leconomiste.com"
    - "www.leconomiste.com"
  # Note: Image extraction uses yoast_head_json.og_image fallback

# ===== EcoActu =====
- name: ecoactu
  type: html
  list_url: "https://ecoactu.ma/economie/economie-nationale/"
  base_url: "https://ecoactu.ma"
  allowed_domains:
    - "ecoactu.ma"
    - "www.ecoactu.ma"
  selectors:
    container: "li.list-post"
    headline: "h2 a"
    link_attr: "href"
    description: "div.item-content p"
    image: "figure img, div.thumbnail img, img"
    date: "time.entry-date"
  image_attrs:
    - "data-src"
    - "src"
  date_regex: "\\b(\\d{1,2})\\s+([A-Za-z\u00c0-\u00ff]+)\\s+(\\d{4})\\b"
  month_map: *fr_months

# ===== Medias24 (WP-JSON API) =====
- name: medias24
  type: wp-json
  api_url: "https://medias24.com/wp-json/wp/v2/posts?categories=14389&per_page=20&_embed"
  base_url: "https://medias24.com"
  allowed_domains:
    - "medias24.com"
    - "www.medias24.com"
