# Finances News
- name: financesnews
  list_url: "https://fnh.ma/articles/actualite-financiere-maroc"
  base_url: "https://fnh.ma"
  selectors:
    container: "div.row"
    headline: "h2 a"
    link_attr: "href"
    description: "div.list_article_detail p"
    image: "img::attr(src)"
    date: "label.itemdate"
  date_regex: '\b(\d{1,2})\s+([A-Za-zéû]+)\s+(\d{4})\b'
  month_map: &month_map
    Janvier: "01"
    Février: "02"
    Mars:    "03"
    Avril:   "04"
    Mai:     "05"
    Juin:    "06"
    Juillet: "07"
    Août:    "08"
    Septembre: "09"
    Octobre:   "10"
    Novembre:  "11"
    Décembre:  "12"

# L’Economiste – Finances & Banques (RSS)
- name: leconomiste
  list_url: "https://www.leconomiste.com/categorie/Finances-Banques/feed"
  base_url: "https://www.leconomiste.com"
  selectors:
    container: "item"
    headline: "title"
    link_attr: "link"
    description: "description"
    image: ""            # el RSS no incluye miniatura
    date: "pubDate"      # «Fri, 26 Jul 2025 09:12:00 +0000»
  date_regex: '(\\d{1,2})\\s+(\\w{3})\\s+(\\d{4})'
  month_map:
    Jan: "01"; Feb: "02"; Mar: "03"; Apr: "04"; May: "05"; Jun: "06"
    Jul: "07"; Aug: "08"; Sep: "09"; Oct: "10"; Nov: "11"; Dec: "12"


# EcoActu – Économie Nationale (RSS)
- name: ecoactu
  list_url: "https://ecoactu.ma/economie/economie-nationale/feed/"
  base_url: "https://ecoactu.ma"
  selectors:
    container: "item"
    headline: "title"
    link_attr: "link"
    description: "description"
    image: ""          # el RSS no trae miniatura fiable
    date: "pubDate"    # «Fri, 26 Jul 2025 08:30:00 +0000»
  date_regex: '(\\d{1,2})\\s+(\\w{3})\\s+(\\d{4})'
  month_map: *month_map


# Bourse de Casablanca
- name: casablanca_bourse
  list_url: "https://www.casablanca-bourse.com/en/insights-institutionnels"
  base_url: "https://www.casablanca-bourse.com"
  selectors:
    container: "div.h-full.flex.flex-col.rounded-lg"
    headline: "h3"
    link_attr: "href"
    description: "a p"
    image: "img::attr(src)"
    date: "p.text-gray-300.text-xs"
  date_regex: '(\d{4})-(\d{2})-(\d{2})'
