# Finances News
- name: financesnews
  list_url: "https://fnh.ma/articles/actualite-financiere-maroc"
  base_url: "https://fnh.ma"
  selectors:
    container: "div.row"
    headline: "h2 a"
    link_attr: "href"
    description: "div.list_article_detail p"
    image: "img::attr(src)"
    date: "label.itemdate"
  date_regex: "\\b(\\d{1,2})\\s+([A-Za-zéû]+)\\s+(\\d{4})\\b"
  month_map:
    Janvier: "01"
    Février: "02"
    Mars: "03"
    Avril: "04"
    Mai: "05"
    Juin: "06"
    Juillet: "07"
    Août: "08"
    Septembre: "09"
    Octobre: "10"
    Novembre: "11"
    Décembre: "12"

# L’Economiste – rubrique Finances & Banques
- name: leconomiste
  list_url: "https://www.leconomiste.com/categorie/Finances-Banques"
  base_url: "https://www.leconomiste.com"
  selectors:
    container: "div.row"
    headline: "h2 a"
    link_attr: "
::contentReference[oaicite:0]{index=0}
